# common paras
common:
  experiment_no: None
  experiment_type: 'pretrain'

  dataset_name: 'ascad_30k'
  init_data_folder: 'init_data/'
  trs_fname: 'ascad_30k_trs.npy'
  label_fname: 'ascad_30k_label.npy'
  plain_fname: 'ascad_30k_plain.npy'
  feature_num: 700
  leakage_model: 'ID'
  classification: 256
  true_key: 224

  disable_cuda: False
  gpu_index: 0

  model_name: 'ascad_cnn'  # ascad_cnn_bn
  batch_size: 500  # 400

# pretrain
pretrain:
  train_num: 0

  # network
  epoch: 200
  lr: 0.00001
  wd: 0.0001

  out_dim: 128
  temperature: 0.07
  n_views: 2

  # data aug
  augmentation:
    data_filter: 1
    data_shift: 5
    data_cut: 5

  # output
  outfile: None

tuning:
  # data para
  train_num: 20000 # 35000
  out_dim: 256 # 9

  # model para
  pretrain_path: ''
  model_eval: False
  frozen: False
  add_dense_bool: False

  optim: 'Adam' # RMSprop
  epoch: 150  # 100
  lr: 0.00001

  # GE para
  GE_epoch: None
  GE_run_time: 100
  GE_every: 10

  # output
  outfile: None

