# common paras
common:
  experiment_no: None
  experiment_type: 'pretrain'

  dataset_name: 'EM_500'
  init_data_folder: 'init_data/'
  trs_fname: 'EM_trs_500.npy'
  label_fname: 'EM_label.npy'
  plain_fname: 'EM_cipher.npy'

  feature_num: 500
  leakage_model: 'HD'
  classification: 9
  true_key: 19

  disable_cuda: False
  gpu_index: 0

  model_name: 'ascad_cnn'  # 'ascad_cnn'  # ascad_cnn_block_anti_bn
  batch_size: 400  # 500

# pretrain
pretrain:
  train_num: 0

  # network
  epoch: 200
  lr: 0.00001
  wd: 0.0001

  out_dim: 128
  temperature: 0.07
  n_views: 2

  # data aug
  augmentation:
    data_filter: 1
    data_shift: 15
    data_cut: 50

  # output
  outfile: None

tuning:
  # data para
  train_num: 35000
  out_dim: 9

  # model para
  pretrain_path: ''
  model_eval: False
  frozen: False
  add_dense_bool: False

  optim: 'Adam' # RMSprop
  epoch: 100  # 150
  lr: 0.00001

  # GE para
  GE_epoch: None
  GE_run_time: 100
  GE_every: 10

  # output
  outfile: None

